@Transient added to the cpassword not to store the value in mongo
SVEPS-ORG/sveps-core-notification pull request #2
Opened 2024-09-27 15:29 UTC by narayana1996

Hi Anna, Can you please accept this changes

2024-09-27 17:34 UTC, nagasaideep-puppala requested changes

2024-09-27 17:34 UTC, nagasaideep-puppala commented on src/main/java/in/co/sveps/contoller/EmployeeController.java
> +                                 Model model) {
USE Employe object like create employe

2024-09-27 17:34 UTC, nagasaideep-puppala commented on src/main/java/in/co/sveps/entity/Employee.java
> -     @Pattern(regexp = "\\d{10}$", message = "Phone number must be 10 digits")
why this chane

2024-09-27 17:34 UTC, nagasaideep-puppala commented on src/main/java/in/co/sveps/entity/Employee.java
> +    //@DBRef
why you are adding

2024-09-27 17:34 UTC, nagasaideep-puppala commented on src/main/java/in/co/sveps/service/EmployeeService.java
> +	public void updateEmployeeFields(ObjectId id, String firstName, String lastName, String email, String phone, List<String> newGroupNames) {
use like create employee. dont get individual fields, and get the data from db and copy the new employee object properties to db object

2024-09-27 17:34 UTC, nagasaideep-puppala commented on src/main/java/in/co/sveps/service/EmployeeService.java
> +		}
use optional java 8 features

2024-09-27 17:34 UTC, nagasaideep-puppala commented on src/main/resources/templates/employeeDetails.html
> +      <label for="newGroups">Add New Groups:</label>
pls provide screen shots for working solution

2024-09-28 06:11 UTC, narayana1996 commented on src/main/java/in/co/sveps/entity/Employee.java
> -     @Pattern(regexp = "\\d{10}$", message = "Phone number must be 10 digits")
Added a line extra, so that the code looks good. no explicit changes on code are done

2024-09-28 06:11 UTC, narayana1996 commented on src/main/java/in/co/sveps/entity/Employee.java
> +    //@DBRef
Added a line extra, so that the code looks good. no explicit changes on code are done

2024-09-28 06:21 UTC, narayana1996 commented on src/main/java/in/co/sveps/service/EmployeeService.java
> +	public void updateEmployeeFields(ObjectId id, String firstName, String lastName, String email, String phone, List<String> newGroupNames) {
done

2024-09-28 06:21 UTC, narayana1996 commented on src/main/java/in/co/sveps/contoller/EmployeeController.java
> +                                 Model model) {
done

2024-09-28 06:26 UTC, narayana1996 commented on src/main/java/in/co/sveps/service/EmployeeService.java
> +		}
done

2024-09-28 06:30 UTC, narayana1996 commented on src/main/resources/templates/employeeDetails.html
> +      <label for="newGroups">Add New Groups:</label>
<img width="278" alt="image" src="https://github.com/user-attachments/assets/5c3e4155-52ff-4e88-bcee-3679f7005a4d">

initial access

<img width="242" alt="image" src="https://github.com/user-attachments/assets/9a0f99a6-122e-49e5-ad94-545cedd7f1cf">

adding asset_read

<img width="296" alt="image" src="https://github.com/user-attachments/assets/bd0cc3e6-2a93-416c-b9a3-917248d327f1">

added new group without effecting old

2024-09-28 20:06 UTC, nagasaideep-puppala approved these changes

2024-09-28 20:06 UTC, merged